version: '3.4'

services:
  xceltech.hrms.api:
    image: xceltechhrmsapi:dev
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "XcelTech.HRMS.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\DELL\Desktop\anotherone3\XcelTech.HRMS\XcelTech.HRMS.Api:/app:rw
      - C:\Users\DELL\Desktop\anotherone3\XcelTech.HRMS:/src:rw
      - C:\Users\DELL\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\DELL\.nuget\packages:/.nuget/packages:ro
      - C:\Users\DELL\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\DELL\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\DELL\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\DELL\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages  \"/app/bin/Debug/net8.0/XcelTech.HRMS.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true